### ISSUE TITLE
SourceCodeRepoType.getType return nullpointexception

### ISSUE THREAD

**Issue by SinhTran** [denimgroup/threadfix#1130]
When I tried to import scans from WhiteHat, I got Null point exception from:

java.lang.NullPointerException
	at com.denimgroup.threadfix.data.entities.SourceCodeRepoType.getType(SourceCodeRepoType.java:47)
	at com.denimgroup.threadfix.service.repository.RepositoryServiceFactory.getRepositoryService(RepositoryServiceFactory.java:52)
	at com.denimgroup.threadfix.service.translator.FindingProcessorFactory.getRootFile(FindingProcessorFactory.java:125)
	at com.denimgroup.threadfix.service.translator.FindingProcessorFactory.getProcessor(FindingProcessorFactory.java:59)
	at com.denimgroup.threadfix.service.translator.PathGuesser.generateGuesses(PathGuesser.java:45)
	at com.denimgroup.threadfix.service.merge.ScanMergerImpl.merge(ScanMergerImpl.java:81)
	at com.denimgroup.threadfix.service.merge.ScanMergerImpl.merge(ScanMergerImpl.java:54)

**Comment by dancornell** [comment]
Didn't you just write that code? ;)

**Comment by SinhTran** [comment]
No. 
I guess it happens when I don't set repository type for application, so application.getRepositoryType() will return null
