### ISSUE TITLE
NoClassDeffound with Threadfix Community Edition 2.2.0 on CloudFoundry

### ISSUE THREAD

**Issue by javabeanz** [denimgroup/threadfix#1191]
2015-06-12T15:43:00.65+0200 [App/0]   OUT Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
2015-06-12T15:43:00.65+0200 [App/0]   OUT 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305)
2015-06-12T15:43:00.65+0200 [App/0]   OUT 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
2015-06-12T15:43:00.65+0200 [App/0]   OUT 	... 46 more
2015-06-12T15:43:00.65+0200 [App/0]   OUT [CONTAINER] org.apache.catalina.core.StandardContext           SEVERE  One or more listeners failed to start. Full details will be found in the appropriate container log file
2015-06-12T15:43:00.66+0200 [App/0]   OUT [CONTAINER] org.apache.catalina.core.StandardContext           SEVERE  Context [] startup failed due to previous errors

**Comment by d-maldonado** [comment]
Do you mind giving a little more information on how you are running ThreadFix?

**Comment by javabeanz** [comment]
I am deploying the community edition War file on a recent cloudfoundry instance with the Go command line client, using java7_buildpack.

**Comment by fredstock** [comment]
Noticed the same problem when trying to run Threadfix within a Docker container.
