### ISSUE TITLE
Unable to start threadfix on ubuntu

### ISSUE THREAD

**Issue by svejdo1** [denimgroup/threadfix#1766]
Using latest version & https://github.com/denimgroup/threadfix/wiki/Ubuntu-and-Debian-Installation-Guide

2016-09-21 10:01:29,553 [http-bio-8080-exec-18] ERROR org.springframework.web.context.ContextLoader (ContextLoader.java:331) - Context ini                                                    tialization failed
org.owasp.esapi.errors.ConfigurationException: java.lang.IllegalArgumentException: Classname cannot be null or empty. Encryptor type name                                                     cannot be null or empty.
        at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:105)
        at org.owasp.esapi.ESAPI.encryptor(ESAPI.java:45)
        at com.denimgroup.threadfix.service.ESAPIEncryptedPropertiesPersister.writeNewPropertiesFile(ESAPIEncryptedPropertiesPersister.jav                                                    a:123)
        at com.denimgroup.threadfix.service.ESAPIEncryptedPropertiesPersister.addAndDecrypt(ESAPIEncryptedPropertiesPersister.java:105)
        at com.denimgroup.threadfix.service.ESAPIEncryptedPropertiesPersister.load(ESAPIEncryptedPropertiesPersister.java:138)
        at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:99)
        at org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(PropertiesLoaderSupport.java:175)
        at org.springframework.core.io.support.PropertiesLoaderSupport.mergeProperties(PropertiesLoaderSupport.java:156)
        at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:80)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistration                                                    Delegate.java:265)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistration                                                    Delegate.java:162)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:                                                    607)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1312)
        at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:690)
        at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:216)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1083)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:640)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Classname cannot be null or empty.
        at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:67)
        ... 49 more

**Comment by d-maldonado** [comment]
svejdo1,

Could you give a few more details of your environment?
- What OS are you using?
- What version of Java do you have installed?
- What version of Tomcat are you deploying with?

Thanks,
Daniel M

**Comment by redonkuless** [comment]
I'm having the same issue:

ubuntu: stretch/sid

JRE v8 as documentation suggest using:
dpkg -s oracle-java8-installer
Package: oracle-java8-installer
Status: install ok installed
Priority: optional
Section: non-free/java
Installed-Size: 91
Maintainer: Alin Andrei <webupd8@gmail.com>
Architecture: all
Version: 8u101+8u101arm-1~webupd8~2
Replaces: icedtea-6-plugin, icedtea-7-plugin, openjdk-6-jre, openjdk-6-jre-headless, openjdk-7-jdk, openjdk-7-jre, openjdk-7-jre-headless, oracle-java7-bin, oracle-java7-fonts, oracle-java7-jdk, oracle-java7-jre, oracle-java7-plugin, oracle-java8-bin, oracle-java8-fonts, oracle-java8-jdk, oracle-java8-jre, oracle-java8-plugin, oracle-jdk7-installer, oracle-jdk8-installer
Provides: default-jre, default-jre-headless, icedtea-6-plugin, icedtea-7-plugin, java-compiler, java-jdk, java-runtime, java-runtime-headless, java-sdk, java-virtual-machine, java2-jdk, java2-runtime, java2-runtime-headless, java2-sdk, java5-jdk, java5-runtime, java5-runtime-headless, java5-sdk, java6-jdk, java6-runtime, java6-runtime-headless, java6-sdk, java7-jdk, java7-runtime, java7-runtime-headless, java7-sdk, java8-jdk, java8-runtime, java8-runtime-headless, java8-sdk, openjdk-6-jre, openjdk-6-jre-headless, openjdk-7-jdk, openjdk-7-jre, openjdk-7-jre-headless, oracle-java7-bin, oracle-java7-fonts, oracle-java7-jdk, oracle-java7-jre, oracle-java7-plugin, oracle-java8-bin, oracle-java8-fonts, oracle-java8-jdk, oracle-java8-jre, oracle-java8-plugin
Depends: java-common (>= 0.24), locales
Pre-Depends: wget, binutils, debconf (>= 0.5) | debconf-2.0
Recommends: gsfonts-x11
Suggests: binfmt-support, visualvm, ttf-baekmuk | ttf-unfonts | ttf-unfonts-core, ttf-kochi-gothic | ttf-sazanami-gothic, ttf-kochi-mincho | ttf-sazanami-mincho, ttf-arphic-uming, firefox | firefox-2 | iceweasel | mozilla-firefox | iceape-browser | mozilla-browser | epiphany-gecko | epiphany-webkit | epiphany-browser | galeon | midbrowser | moblin-web-browser | xulrunner | xulrunner-1.9 | konqueror | chromium-browser | midori | google-chrome
Conflicts: j2se-common
Description: Oracle Java(TM) Development Kit (JDK) 8
 The JDK(TM) is a development environment for building and running
 applications, applets, and components using the Java programming language.
 .
 The JDK(TM) includes Java Runtime Environment (JRE) for running applications,
 Java Plug-in for running applets in web browsers and tools useful for
 developing and testing programs written in the Java programming language.
 .
 Note that this package does not contain any software from Oracle. This
 package does however contain a script to download and install Oracle JDK 8.
 All information regarding Java itself can be found on this website:
 http://www.oracle.com/
Homepage: http://jdk8.java.net/download.html
Npp-Applications: ec8030f7-c20a-464f-9b0e-13a3a9e97384, 92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a
Npp-Mimetype: application/x-java-vm, application/x-java-applet, application/x-java-applet;version=1.1, application/x-java-applet;version=1.1.1, application/x-java-applet;version=1.1.2, application/x-java-applet;version=1.1.3, application/x-java-applet;version=1.2, application/x-java-applet;version=1.2.1, application/x-java-applet;version=1.2.2, application/x-java-applet;version=1.3, application/x-java-applet;version=1.3.1, application/x-java-applet;version=1.4, application/x-java-applet;version=1.4.1, application/x-java-applet;version=1.4.2, application/x-java-applet;version=1.5, application/x-java-applet;version=1.6, application/x-java-applet;jpi-version=1.6.0_07, application/x-java-bean, application/x-java-bean;version=1.1, application/x-java-bean;version=1.1.1, application/x-java-bean;version=1.1.2, application/x-java-bean;version=1.1.3, application/x-java-bean;version=1.2, application/x-java-bean;version=1.2.1, application/x-java-bean;version=1.2.2, application/x-java-bean;version=1.3, application/x-java-bean;version=1.3.1, application/x-java-bean;version=1.4, application/x-java-bean;version=1.4.1, application/x-java-bean;version=1.4.2, application/x-java-bean;version=1.5, application/x-java-bean;version=1.6, application/x-java-bean;jpi-version=1.8.0_b54, application/x-java-jnlp-file
Npp-Name: The Java(TM) Plug-in, Java SE 8
root@ubuntu:/var/lib/tomcat7/webapps# 

I'm using tomcat7 from ubuntu repository, and I'm doing that because the documentation on the wiki is outdated for newer versions of ubuntu upstart is no longer supported or used.
